import dayjs from "dayjs";
import { ReactNode } from "react";
import { Config, Coords, Day, SchedulerData, ZoomLevel } from "@/types/global";
import { ParsedDatesRange } from "@/utils/getDatesRange";

export type CalendarContextType = {
  handleGoNext: () => void;
  handleScrollNext: () => void;
  handleGoPrev: () => void;
  handleScrollPrev: () => void;
  handleGoToday: () => void;
  changeZoom: (zoomLevel: number) => void;
  zoomIn: () => void;
  zoomOut: () => void;
  handleFilterData: () => void;
  updateTilesCoords: (coords: Coords[]) => void;
  onClearFilterData?: () => void;
  leftHeaderRender?: (props: any) => ReactNode;
  rightHeaderRender?: (props: any) => ReactNode;
  centerHeaderRender?: (props: any) => ReactNode;
  headerRender?: (props: any) => ReactNode;
  scrollToLoadData?: boolean;
  data?: SchedulerData;
  tilesCoords: Coords[];
  zoom: ZoomLevel;
  isNextZoom: boolean;
  isPrevZoom: boolean;
  date: dayjs.Dayjs;
  isLoading: boolean;
  cols: number;
  startDate: Day;
  dayOfYear: number;
  recordsThreshold: number;
  config: Config;
};

export type CalendarProviderProps = {
  children: ReactNode;
  isLoading: boolean;
  defaultStartDate?: dayjs.Dayjs;
  data?: SchedulerData;
  config: Config;
  onRangeChange?: (range: ParsedDatesRange) => void;
  onFilterData?: () => void;
  onClearFilterData?: () => void;
  leftHeaderRender?: (props: any) => ReactNode;
  rightHeaderRender?: (props: any) => ReactNode;
  centerHeaderRender?: (props: any) => ReactNode;
  headerRender?: (props: any) => ReactNode;
  scrollToLoadData?: boolean;
};
